Added tutorial links for instruction 00, 01, 02
apuder/iot-workshop pull request #3
Opened 2018-07-05 03:59 UTC by LijieZhou

2018-07-05 17:13 UTC, apuder requested changes
Please reformat the link as I suggested in my comment. Also, rebase to origin/master and get rid of commit b90f824. Change the comments for each commit to indicate for which tutorial this commit is for (e.g., "Add link for tutorial 00"). Then force-push for a clean history. Thx.

2018-07-05 17:13 UTC, apuder commented on 00/README.md
> +
I suggest to embed the link like this:
Link to <a href="https://youtube.com/...">video tutorial</a>.

I also suggest to add those links at the bottom of each respective page. Please change for the three videos you have made so far.

2018-07-05 22:42 UTC, LijieZhou commented
I have sent another pull request with new changes based on your comments.

2018-07-06 03:41 UTC, merged

2018-07-06 03:42 UTC, apuder commented
Thanks for your contribution. Looking forward to the next videos. :)

2018-07-06 20:53 UTC, shaeberling commented on 00/README.md
> +Tutorial [link](https://www.youtube.com/watch?v=GcfJXjz86n0&list=PL2prrfB4uRarl12GHSbsoMmeYYlk2PLb7&t=4s&index=4)
&t=4s will start the video 4 seconds int, cutting of part of the narrative. That's probably not what you want?

2018-07-06 20:53 UTC, shaeberling commented on 01/README.md
> +Tutorial [link](https://www.youtube.com/watch?v=QSwEKkHwWP4&list=PL2prrfB4uRarl12GHSbsoMmeYYlk2PLb7&t=0s&index=3)
"&t=0s" does nothing (sets an offset of 0)

2018-07-06 20:53 UTC, shaeberling commented on 02/README.md
> +Tutorial [link](https://www.youtube.com/watch?v=qr91fY0JsOU&list=PL2prrfB4uRarl12GHSbsoMmeYYlk2PLb7&t=0s&index=2)
Same here, "&t=0s" does nothing.

2018-07-08 17:30 UTC, apuder commented
@LijieZhou: I think @shaeberling made some valid comments, especially regarding the t=4s. On second thought I would also suggest to embed the YouTube videos instead of adding a link. Why don't you create a new PR with those fixes for the first three videos?

2018-07-09 18:32 UTC, LijieZhou commented
@apuder Did some research on embeded video on YouTube, and seems like it is not currently supported (except the github.io page). However, I can embed an clickable image to take the reader to the video. 
https://stackoverflow.com/questions/11804820/embed-a-youtube-video
Does that work? If so, I will use this trick and fix the glitch pointed out by @shaeberling

2018-07-11 00:16 UTC, apuder commented
@LijieZhou the procedure posted on SO is a good compromise. Please make those changes. You can put them all in one PR with three commits for each of the three tutorials. Thx.